apiVersion: apps/v1
kind: Deployment
metadata:
  name: music-server-deployment
  labels:
    app: music-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: music-server
  template:
    metadata:
      labels:
        app: music-server
    spec:
      containers:
        - name: music-server
          image: musicweb-music-server:latest
          ports:
            - containerPort: 8888
#          volumeMounts:
#            - name: secret-volume
#              mountPath: /etc/secrets
#              readOnly: true
#volumeMounts:
#  - name: config-volume
#    mountPath: /etc/config
#    readOnly: true
#
#volumes:
#  - name: config-volume
#    configMap:
#      name: app-config