# 使用 Node.js 18.20.0 作为基础镜像
FROM node:18.20.0-alpine AS build
WORKDIR /app
# 复制 package.json 和 package-lock.json 并安装依赖
COPY package*.json ./
RUN npm install
# 复制项目的其余部分并进行构建
COPY . .
RUN npm run build
# 使用 Nginx 提供服务
FROM nginx:alpine
# 将构建后的文件从构建阶段复制到nginx的默认目录
COPY --from=build /app/dist /usr/share/nginx/html
# 暴露nginx端口
EXPOSE 80
# 启动nginx
CMD ["nginx", "-g", "daemon off;"]
