# 使用 OpenJDK 21 作为基础镜像
FROM openjdk:21
WORKDIR /app
# 复制打包好的JAR文件
COPY target/*.jar /app/music-server.jar
# 暴露Spring Boot应用的端口
EXPOSE 8080
# 运行Spring Boot应用
ENTRYPOINT ["java", "-jar", "music-server.jar"]